<?php
// Frontend configuration
// This file is automatically generated by the user data script

// Try to read from environment variables first
$app_alb_dns = getenv('APP_ALB_DNS') ?: '';
$project_name = getenv('PROJECT_NAME') ?: 'three-tier-app';
$environment = getenv('ENVIRONMENT') ?: 'production';

// If not set in environment, try to read from a config file
if (empty($app_alb_dns) && file_exists('/etc/three-tier/config.ini')) {
    $config = parse_ini_file('/etc/three-tier/config.ini');
    $app_alb_dns = $config['APP_ALB_DNS'] ?? '';
}

// Final fallback
if (empty($app_alb_dns)) {
    $app_alb_dns = 'http://app-alb.internal'; // Internal DNS name pattern
}

// Output JavaScript configuration
echo "<script>\n";
echo "window.APP_ALB_DNS = '" . addslashes($app_alb_dns) . "';\n";
echo "window.PROJECT_NAME = '" . addslashes($project_name) . "';\n";
echo "window.ENVIRONMENT = '" . addslashes($environment) . "';\n";
echo "</script>\n";
?>